kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username: yichuan95
    password: 4df5faa8-4e1d-4a26-b8fe-69bc61f0dcef
    repo: yichuan95/dotnetcore-container
    dockerfile: Web/Dockerfile
