kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username: yichuan95
    password:
      from_secret: mydronesecret
    repo: yichuan95/dotnetcore-container
    dockerfile: Web/Dockerfile
